name: Release
on:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test
        run: go test -v ./...

  push:
    name: Push
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ steps.commit.outputs.short }}

  deployStg:
    name: Deploy Staging
    runs-on: ubuntu-latest
    needs: push
    container:
      image: docker.io/bitnami/kubectl:1.29.0
    steps:
      - name: "Patch Image"
        run: |
          echo $KUBE_CONFIG | base64 -d > kc.yaml
          kubectl --kubeconfig kc.yaml set image deployment/profile-staging svc=$NEW_IMAGE
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
          NEW_IMAGE: ${{ needs.push.outputs.tags }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: push
    container:
      image: docker.io/bitnami/kubectl:1.29.0
    steps:
      - name: "Patch Image"
        run: |
          echo $KUBE_CONFIG | base64 -d > kc.yaml
          kubectl --kubeconfig kc.yaml set image deployment/profile svc=$NEW_IMAGE
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
          NEW_IMAGE: ${{ needs.push.outputs.tags }}
